services:
  web:
    container_name: WeddingApp
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    networks:
      - wedding
    ports:
      - "5000:5000"


networks:
  wedding: { }

